---
# This playbook uses the Azure ansible modules to create a VM in Azure.
# You need to have the service principle details as per the dependencies in the tutorial

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group_name: learnAnsibleRG
    location: uksouth
    vnet_name: myVnet
    subnet_name: mySubnet
    public_ip_name: myPublicIP
    nsg_name: myNetworkSecurityGroup
    nic_name: myNIC
    vm_name: myVM
    vm_size: Standard_DS1_v2
    vm_username: adminuser
    key_data: "PUBLIC_KEY_DATA"
  tasks:
  - name: Create resource group
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ location }}"
  - name: Create virtual network
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vnet_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: "{{ resource_group_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vnet_name }}"
  - name: Create public IP address
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: "{{ resource_group_name }}"
      allocation_method: Static
      name: "{{ public_ip_name }}"
    register: output_ip_address
  - name: Public IP of VM
    ansible.builtin.debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH and HTTP
    azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ resource_group_name }}"
      name: "{{ nsg_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
  - name: Create virtual network interface card
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group_name }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ subnet_name }}"
      security_group: "{{ nsg_name }}"
      ip_configurations:
      - name: ipconfig1
        public_ip_address_name: "{{ public_ip_name }}"
        primary: true
  - name: Create VM
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vm_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ vm_username }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "/home/{{ vm_username }}/.ssh/authorized_keys"
          key_data: "{{ key_data }}"
      network_interfaces: "{{ nic_name }}"
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts
        version: latest
  - name: Public IP of VM
    ansible.builtin.debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."