---
- hosts: localhost
  vars:
    name: learnAnsibleRG
  tasks:
    - name: Deleting resource group - "{{ name }}"
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ name }}"
        state: absent
        force_delete_nonempty: true
      register: rg
    - name: Print Resource Group Deletion Output
      ansible.builtin.debug:
        var: rg